org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# 配置 Gradle 使用本地代理
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18864
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18864
# 忽略本地地址的代理
systemProp.http.nonProxyHosts=localhost|127.*|[::1]
systemProp.https.nonProxyHosts=localhost|127.*|[::1]